[feat] Support post processing predict as learnt and predict on cells for surface variables
ansys/pysimai pull request #117
Opened 2024-12-24 15:38 UTC by yias

## Description

This PR enables users to trigger post-processing on surface variables with location options; `on cells` or `as learnt`. 

To manage the selection of endpoints for the two options, the classes `PostProcessingOnCells` and `PostProcessingAsLearnt` are introduced as child-classes of `SurfaceVTP`. These choices are enumerated in `PPSurfaceLocation`. The methods `PredictionPostProcessings.surface_vtp` and `SelectionPostProcessingsMethods.surface_vtp` have now the argument `pp_location`, which should be one enumeration option of `PPSurfaceLocation`. The default option is set to 

Story: [sc-26496]

## Tests
- Unit-tests added
- Interactive smoke testing against dev env.

PS. It requires merging the corresponding PR of the API support.

2024-12-26 11:10 UTC, tmpbeing reviewed
I think class names need to change. And we might want to turn `SurfaceVTP` into `_SurfaceVTP` and undocument it if it's not meant to be used directly anymore. Hell maybe remove it entirely given the class is empty.

2024-12-26 11:10 UTC, tmpbeing commented on doc/source/api_reference/post_processings.rst
> +    :members:
Might want to have inherited-members as well.

2024-12-26 11:10 UTC, tmpbeing commented on src/ansys/simai/core/data/post_processings.py
> +class PostProcessingOnCells(SurfaceVTP):
I didn't follow the product story but these class name seems too generic. Maybe `SurfaceOnCells` and `SurfaceAsLearnt` ?

2025-01-08 16:06 UTC, yias commented on src/ansys/simai/core/data/post_processings.py
> +class PostProcessingOnCells(SurfaceVTP):
My intention is to follow the naming as in the description of the story; since the post-processing is described as `predict on cells`, where `cells` are the data under the `cell` keyword in pyvista objects, I assume that this name would be self-explanatory to users. Nevertheless, please feel free to bring any suggestions on.

2025-01-08 16:19 UTC, yias commented
Conceptually, both objects of `PostProcessingOnCells` and of `PostProcessingAsLearnt()` are `SurfaceVTP` objects, since the resource is a surface vtp file. Their only deference is the endpoint. If we need to do any processing on the returned (by both options) surface vtp file, it would be realized in the `SurfaceVTP` class. This is the reason I let it as is. @tmpbeing let me know what you think.

2025-01-09 11:30 UTC, awoimbee reviewed
> Conceptually, both objects of PostProcessingOnCells and of PostProcessingAsLearnt() are SurfaceVTP objects, since the resource is a surface vtp file. Their only deference is the endpoint. If we need to do any processing on the returned (by both options) surface vtp file, it would be realized in the SurfaceVTP class.

But the `SurfaceVTP` class is an empty shell here ? So it does not do any processing ?

2025-01-09 11:38 UTC, yias commented
@awoimbee it does not do any processing right now, but in future any processing needs to be done for surface vtp file the SurfaceVTP class would be the right place to realize them. Regarding the naming of the classes, it is a product question and I asked PM for that (see linked story).

2025-01-09 11:41 UTC, yias commented on src/ansys/simai/core/data/post_processings.py
> +        self, run: bool = True, pp_location: PPSurfaceLocation = PPSurfaceLocation.ON_CELLS
An enum might require a little bit of more coding from the part of the users, but it is a more structured way to control the input of arguments, than strings. This is way I used it here.

2025-01-09 16:26 UTC, yias commented on src/ansys/simai/core/data/post_processings.py
> +class PostProcessingOnCells(SurfaceVTP):
PM has accepted the suggestion on the classes names, resolving the comment.

2025-01-09 16:28 UTC, yias commented
class `SurfaceVTP` has been renamed to `_SurfaceVTP` and removed from documentation. Suggestion on class names is accepted by PM. Please review.

2025-01-09 16:55 UTC, tmpbeing approved these changes
If PM is happy

2025-01-09 17:02 UTC, yias commented
I just realized that `SurfaceVTP` is the type of post-processing that the BE returns in the response body when requesting surface post-processing. Since the method `.model_from` uses the type of the response for creating instances of this type, `SurfaceVTP` is tight to the BE response. To me, this qualifies it as a class name, so I'm bringing back its original name (by removing `_`).

2025-01-10 09:59 UTC, tmpbeing requested changes
> I just realized that SurfaceVTP is the type of post-processing that the BE returns in the response body when requesting surface post-processing. Since the method .model_from uses the type of the response for creating instances of this type, SurfaceVTP is tight to the BE response. To me, this qualifies it as a class name, so I'm bringing back its original name (by removing _).

Ok this is actually a bit of a red flag. If I understand correctly that means we create different classes in different contexts for the same thing. Looking at `model_from` and specifically `_data_model_for_type_name` it seems we'll get an error if we get a `SurfaceVTPTDLocation` from the backend.

2025-01-10 10:52 UTC, misterjoa commented on src/ansys/simai/core/data/post_processings.py
> +class PostProcessingOnCells(SurfaceVTP):
Hello everyone! I was just reading this PR when I fell upon this thread. It seems that comments have been discarded without finding agreement between everyone. Let's discuss this together this afternoon, I'll schedule a meeting!

2025-01-10 11:50 UTC, yias commented
@tmpbeing We would get an error if BE would return `SurfaceVTPTDLocation`, however it does not return `SurfaceVTPTDLocation`. It returns `SurfaceVTP` for post-processing on surface vars (both for predict as learnt and predict on cells), and this is why it doesn't break. Let me know what you think

2025-01-15 15:16 UTC, yias commented on src/ansys/simai/core/data/post_processings.py
> +        self, run: bool = True, pp_location: PPSurfaceLocation = PPSurfaceLocation.ON_CELLS
since a new method is introduced, this discussion is outdated. Thus, I'm resolving it

2025-01-15 15:47 UTC, yias commented
PR is updated as discussed in our meeting. Reviews are welcomed, thanks.

2025-01-23 16:31 UTC, awoimbee approved these changes

2025-01-23 16:56 UTC, merged